services:
  postgres:
    container_name: "welnex-postgres"
    image: "postgres:latest"
    restart: "unless-stopped"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    container_name: welnex-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.redis:/data

  api:
    container_name: "welnex-api"
    image: "welnex-api:latest"
    depends_on:
      - postgres
    restart: "unless-stopped"
    environment:
      - CONFIG_PATH=./config/dev.yaml
    ports:
      - "6969:6969"
