env: "local" # local, dev or prod

server:
  address: ":6969"
  timeout: 4s
  idle_timeout: 60s

token:
  secret: "your-supa-secret-letters"

postgres:
  host: "localhost"
  port: "1337"
  user: "postgres"
  name: "postgres"
  password: "my-unhackable-password"
  sslmode: "false"
