name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.5"

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -o ./bin/api ./cmd/api
