name: Push image to DockerHub

on:
  push:
    branches:
      - master
      - develop

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t jus1d/dreik-api:latest .

      - name: Push Docker image
        run: |
          docker push jus1d/dreik-api:latest