name: Testing

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21.x", "1.22.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Build project
        run: go build -o ./bin/api ./cmd/api

      - name: Run tests
        run: go test ./...
